{% set name = "librealsense" %}
{% set version = "2.53.1" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/IntelRealSense/librealsense/archive/v{{ version }}.tar.gz
    sha256: e09d0cca0316fa02427ce749c4e9cc8d34e3a86c127b32a8dca3ef483e71e908
    patches:
      - fix_macos_arm64.patch

build:
  number: 1
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
  skip: true  # [win]
  track_features: {{ "[librealsense-cuda]" if cuda_enabled else "" }}
  run_exports:
    # See https://github.com/IntelRealSense/librealsense/pull/3449
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja
    - libudev  # [linux]
  host:
    - libusb


test:
  commands:
    - test -f ${PREFIX}/include/librealsense2/rs.hpp  # [not win]
    - test -f ${PREFIX}/lib/librealsense2.so  # [linux]
    - test -f ${PREFIX}/lib/librealsense2.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/realsense2/realsense2Config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\librealsense2\\rs.hpp (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\realsense2.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\realsense2.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\cmake\\realsense2\\realsense2Config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/IntelRealSense/librealsense
  license: Apache-2.0
  license_file: LICENSE
  summary: Cross-platform library for Intel® RealSense™ depth and tracking cameras.

extra:
  recipe-maintainers:
    - traversaro
